package com.github.KamilKurde.Kalc.units.operationSpeed

import com.github.KamilKurde.Kalc.units.OperationSpeed.OperationSpeed

val Number.YOPH get() = OperationSpeed(this, OperationSpeedUnits.YOPH)
val Number.ZOPH get() = OperationSpeed(this, OperationSpeedUnits.ZOPH)
val Number.EOPH get() = OperationSpeed(this, OperationSpeedUnits.EOPH)
val Number.POPH get() = OperationSpeed(this, OperationSpeedUnits.POPH)
val Number.TOPH get() = OperationSpeed(this, OperationSpeedUnits.TOPH)
val Number.GOPH get() = OperationSpeed(this, OperationSpeedUnits.GOPH)
val Number.MOPH get() = OperationSpeed(this, OperationSpeedUnits.MOPH)
val Number.KOPH get() = OperationSpeed(this, OperationSpeedUnits.KOPH)
val Number.OPH get() = OperationSpeed(this, OperationSpeedUnits.YOPH)
val Number.YOPM get() = OperationSpeed(this, OperationSpeedUnits.YOPM)
val Number.ZOPM get() = OperationSpeed(this, OperationSpeedUnits.ZOPM)
val Number.EOPM get() = OperationSpeed(this, OperationSpeedUnits.EOPM)
val Number.POPM get() = OperationSpeed(this, OperationSpeedUnits.POPM)
val Number.TOPM get() = OperationSpeed(this, OperationSpeedUnits.TOPM)
val Number.GOPM get() = OperationSpeed(this, OperationSpeedUnits.GOPM)
val Number.MOPM get() = OperationSpeed(this, OperationSpeedUnits.MOPM)
val Number.KOPM get() = OperationSpeed(this, OperationSpeedUnits.KOPM)
val Number.OPM get() = OperationSpeed(this, OperationSpeedUnits.YOPM)
val Number.YOPS get() = OperationSpeed(this, OperationSpeedUnits.YOPS)
val Number.ZOPS get() = OperationSpeed(this, OperationSpeedUnits.ZOPS)
val Number.EOPS get() = OperationSpeed(this, OperationSpeedUnits.EOPS)
val Number.POPS get() = OperationSpeed(this, OperationSpeedUnits.POPS)
val Number.TOPS get() = OperationSpeed(this, OperationSpeedUnits.TOPS)
val Number.GOPS get() = OperationSpeed(this, OperationSpeedUnits.GOPS)
val Number.MOPS get() = OperationSpeed(this, OperationSpeedUnits.MOPS)
val Number.KOPS get() = OperationSpeed(this, OperationSpeedUnits.KOPS)
val Number.OPS get() = OperationSpeed(this, OperationSpeedUnits.YOPS)